
import { Language, Product } from './types';

export const TRANSLATIONS = {
  [Language.ENGLISH]: {
    appName: "Texpress",
    home: "Home",
    settings: "Settings",
    signIn: "Sign In",
    signOut: "Sign Out",
    language: "Language",
    currency: "Currency",
    darkMode: "Dark Mode",
    admin: "Admin",
    addProduct: "Add Product",
    editProduct: "Edit Product",
    name: "Name",
    price: "Price",
    weight: "Weight",
    description: "Description",
    save: "Save",
    cancel: "Cancel",
    addToCart: "Add to Cart",
    buyNow: "Buy Now",
    reviews: "Reviews",
    leaveReview: "Leave a Review",
    submit: "Submit",
    password: "Password",
    adminHint: "Admin password is 1212",
    cart: "Cart",
    emptyCart: "Your cart is empty",
    items: "items",
    total: "Total",
    kg: "kg",
    search: "Search products..."
  },
  [Language.ARABIC]: {
    appName: "تيكسبرس",
    home: "الرئيسية",
    settings: "الإعدادات",
    signIn: "تسجيل الدخول",
    signOut: "تسجيل الخروج",
    language: "اللغة",
    currency: "العملة",
    darkMode: "الوضع المظلم",
    admin: "مسؤول",
    addProduct: "إضافة منتج",
    editProduct: "تعديل المنتج",
    name: "الاسم",
    price: "السعر",
    weight: "الوزن",
    description: "الوصف",
    save: "حفظ",
    cancel: "إلغاء",
    addToCart: "أضف إلى السلة",
    buyNow: "اشتر الآن",
    reviews: "التقييمات",
    leaveReview: "اترك تقييماً",
    submit: "إرسال",
    password: "كلمة المرور",
    adminHint: "كلمة سر المسؤول هي 1212",
    cart: "السلة",
    emptyCart: "سلتك فارغة",
    items: "عناصر",
    total: "الإجمالي",
    kg: "كجم",
    search: "بحث عن منتجات..."
  },
  [Language.FRENCH]: {
    appName: "Texpress",
    home: "Accueil",
    settings: "Paramètres",
    signIn: "Connexion",
    signOut: "Déconnexion",
    language: "Langue",
    currency: "Devise",
    darkMode: "Mode Sombre",
    admin: "Admin",
    addProduct: "Ajouter Produit",
    editProduct: "Modifier Produit",
    name: "Nom",
    price: "Prix",
    weight: "Poids",
    description: "Description",
    save: "Enregistrer",
    cancel: "Annuler",
    addToCart: "Ajouter au Panier",
    buyNow: "Acheter",
    reviews: "Avis",
    leaveReview: "Laisser un avis",
    submit: "Envoyer",
    password: "Mot de passe",
    adminHint: "Mot de passe admin: 1212",
    cart: "Panier",
    emptyCart: "Votre panier est vide",
    items: "articles",
    total: "Total",
    kg: "kg",
    search: "Rechercher..."
  }
};

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'X-Pro Headphones',
    price: 299,
    weight: 0.35,
    description: 'Noise cancelling premium audio experience with 40-hour battery life.',
    images: ['https://picsum.photos/id/26/600/600', 'https://picsum.photos/id/27/600/600'],
    attributes: [{ key: 'Color', value: 'Matte Black' }],
    reviews: [],
    category: 'Electronics'
  },
  {
    id: '2',
    name: 'Texpress Smart Watch',
    price: 199,
    weight: 0.12,
    description: 'Sleek design with full health tracking features and OLED display.',
    images: ['https://picsum.photos/id/48/600/600', 'https://picsum.photos/id/49/600/600'],
    attributes: [{ key: 'Waterproof', value: 'IP68' }],
    reviews: [],
    category: 'Wearables'
  },
  {
    id: '3',
    name: 'Minimalist Backpack',
    price: 89,
    weight: 0.8,
    description: 'Water resistant material with a 15-inch laptop compartment.',
    images: ['https://picsum.photos/id/160/600/600', 'https://picsum.photos/id/161/600/600'],
    attributes: [{ key: 'Material', value: 'Canvas' }],
    reviews: [],
    category: 'Fashion'
  },
  {
    id: '4',
    name: 'Ergonomic Mouse',
    price: 59,
    weight: 0.15,
    description: 'Precision tracking with adjustable DPI and vertical design.',
    images: ['https://picsum.photos/id/180/600/600'],
    attributes: [{ key: 'Buttons', value: '6' }],
    reviews: [],
    category: 'Accessories'
  }
];
